/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "BunkSpot_Auth": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "BunkSpot_Master": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BunkSpot_PWA": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
    "WebClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}