/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_TABLE_NAME: string
  readonly VITE_USER_POOL_ID: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}